
services:
  zookeeper:
    image: zookeeper:3.9.1
    container_name: zookeeper-worker
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  #Kafka donde se publicaran los mensajes de los pedidos
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka-worker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka-worker
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper #Kafka no inicia hasta que zookeeper este listo

  #MongoDb
  mongodb:
    image: mongo:6.0
    container_name: mongodb-worker
    ports:
      - "27017:27017"
  
  #Gestion de estado y bloqueos (redis)
  redis:
    image: redis:7.0-alpine
    container_name: redis-worker
    ports:
      - "6379:6379"

  # Api Go
  catalog-go:
    build:
      context: ../catalog-service-go  # Ruta a la carpeta de tu proyecto Go
      dockerfile: DockerFile.yml
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  # Java Worker
  worker-java:
    build:
      context: ../catalog-service-java
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mongodb
      - redis
      - catalog-go

#Aqui simplemente se listan para que docker sepa que existen
volumes:
  mongo_data:
  redis_data: